<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Allows to add pages (markdown, iframe or links) to the space navigation' => '',
    'Custom pages' => '',
    'Without adding to navigation (Direct link)' => '',
    'Create new Page' => 'Crea nuova pagina',
    'Custom Pages' => 'Pagine personalizzate',
    'HTML' => 'HTML',
    'IFrame' => 'IFrame',
    'Link' => 'Link',
    'MarkDown' => 'MarkDown',
    'Navigation' => 'Menu',
    'No custom pages created yet!' => 'Nessun pagina ancora creata!',
    'Sort Order' => 'Ordinamento',
    'Title' => 'Titolo',
    'Top Navigation' => 'Top Menu',
    'Type' => 'Tipo',
    'User Account Menu (Settings)' => 'Menu impostazione per utenti',
];
