<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Allows to add pages (markdown, iframe or links) to the space navigation' => '',
    'Custom pages' => '',
    'Without adding to navigation (Direct link)' => '',
    'Create new Page' => 'Crear nueva página',
    'Custom Pages' => 'Páginas personalizadas',
    'HTML' => 'HTML',
    'IFrame' => 'IFrame',
    'Link' => 'Link',
    'MarkDown' => 'MarkDown',
    'Navigation' => 'Navegación',
    'No custom pages created yet!' => '¡No se han creado páginas personalizadas todavía!',
    'Sort Order' => 'Orden de clasificación',
    'Title' => 'Título',
    'Top Navigation' => 'Navegación superior',
    'Type' => 'Tipo',
    'User Account Menu (Settings)' => 'Menú de cuenta de usuario (ajustes)',
    '<strong>Custom</strong> Pages' => '',
    'Back to overview' => '',
    'Overview' => '',
    'Pages' => '',
    'Snippets' => '',
    'Templates' => '',
    'Please choose one of the following content types. The content type defines how your content is embeded to your site.' => '',
    'Add' => '',
    'Iframe' => '',
    'Template' => '',
    'Html' => '',
    'Allows you to add content in MarkDown syntax.' => '',
    'Adds plain HTML content to your site.' => '',
    'Templates allow you to define combinable page fragments with inline edit functionality.' => '',
    'Will embed the the result of a given url as an iframe element.' => '',
    'Will redirect requests to a given (relative or absolute) url.' => '',
    'Dashboard' => '',
    'Directory' => '',
    'Saved' => '',
    'This container does not allow any further items!' => '',
    'This action requires an ownerContentId or ownerContent instance!' => '',
    'This action requires an templateId or template instance!' => '',
    'General' => '',
    'Source' => '',
    'Save' => '',
    'Create new {type}' => '',
    'Close' => '',
    'Delete' => '',
    'Cancel' => '',
    'Layouts' => '',
    'Snipped-Layouts' => '',
    'Containers' => '',
    'Submit' => '',
    'An empty allowed template selection will allow all container templates for this container.' => '',
    'Default Content' => '',
    'Content' => '',
    'Reset' => '',
    'Back' => '',
    '<strong>No file available.</strong>' => '',
    'Upload' => '',
    '<strong>No image available.</strong>' => '',
    'Edit On' => '',
    'Edit Off' => '',
    'Edit Page' => '',
    'Default' => '',
    'Empty' => '',
];
