<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Allows to add pages (markdown, iframe or links) to the space navigation' => '',
    'Custom pages' => '',
    'Without adding to navigation (Direct link)' => '',
    'Create new Page' => 'Crear nueva página',
    'Custom Pages' => 'Páginas personalizadas',
    'HTML' => 'HTML',
    'IFrame' => 'IFrame',
    'Link' => 'Link',
    'MarkDown' => 'MarkDown',
    'Navigation' => 'Navegación',
    'No custom pages created yet!' => '¡No se han creado páginas personalizadas todavía!',
    'Sort Order' => 'Orden de clasificación',
    'Title' => 'Título',
    'Top Navigation' => 'Navegación superior',
    'Type' => 'Tipo',
    'User Account Menu (Settings)' => 'Menú de cuenta de usuario (ajustes)',
];
