<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Allows to add pages (markdown, iframe or links) to the space navigation' => '',
    'Custom pages' => '',
    'Create new Page' => '新しいページを作成します',
    'Custom Pages' => 'カスタム ページ',
    'HTML' => 'HTML',
    'IFrame' => 'IFrame',
    'Link' => 'リンク',
    'MarkDown' => 'Markdown',
    'Navigation' => 'ナビゲーション',
    'No custom pages created yet!' => 'カスタム ページがありません!',
    'Sort Order' => '並べ替え順序',
    'Title' => 'タイトル',
    'Top Navigation' => 'トップ ナビゲーション',
    'Type' => 'タイプ',
    'User Account Menu (Settings)' => 'ユーザー アカウント メニュー (設定)',
    'Without adding to navigation (Direct link)' => '(直接リンク) ナビゲーションに追加しません。',
];
