<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Allows to add pages (markdown, iframe or links) to the space navigation' => '',
    'Custom pages' => '',
    'Create new Page' => 'Créer une nouvelle page',
    'Custom Pages' => 'Pages personnalisées',
    'HTML' => 'HTML',
    'IFrame' => 'IFrame',
    'Link' => 'Lien',
    'MarkDown' => 'MarkDown',
    'Navigation' => 'Menu de navigation',
    'No custom pages created yet!' => 'Aucune page personnalisée n\'a été créée !',
    'Sort Order' => 'Ordre de tri',
    'Title' => 'Titre',
    'Top Navigation' => 'Menu de navigation',
    'Type' => 'Type',
    'User Account Menu (Settings)' => 'Menu du compte utilisateur (paramètres)',
    'Without adding to navigation (Direct link)' => 'Sans l\'ajouter au menu de navigation (lien direct)',
];
