<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Allows to add pages (markdown, iframe or links) to the space navigation' => '允许添加页面 (markdown标记语言, iframe框架 或链接) 到空间导航',
    'Create new Page' => '创建新页面',
    'Custom Pages' => '自定义页面',
    'Custom pages' => '自定义页面',
    'HTML' => 'HTML页面',
    'IFrame' => 'IFrame框架',
    'Link' => '链接',
    'MarkDown' => 'MarkDown标记语言',
    'Navigation' => '导航',
    'No custom pages created yet!' => '目前还没有创建自定义页面！',
    'Sort Order' => '排序',
    'Top Navigation' => '顶部导航',
    'Type' => '类型',
    'User Account Menu (Settings)' => '用户帐户菜单(设置)',
    'Without adding to navigation (Direct link)' => '不添加导航（直接链接）',
    'Title' => '标题',
];
