<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Allows to add pages (markdown, iframe or links) to the space navigation' => '允许添加页面 (markdown标记语言, iframe框架 或链接) 到空间导航',
    'Create new Page' => '创建新页面',
    'Custom Pages' => '自定义页面',
    'Custom pages' => '自定义页面',
    'HTML' => 'HTML页面',
    'IFrame' => 'IFrame框架',
    'Link' => '链接',
    'MarkDown' => 'MarkDown',
    'Navigation' => '导航',
    'No custom pages created yet!' => '目前还没有创建自定义页面！',
    'Sort Order' => '排序',
    'Top Navigation' => '顶部导航',
    'Type' => '类型',
    'User Account Menu (Settings)' => '用户帐户菜单(设置)',
    'Without adding to navigation (Direct link)' => '不添加导航（直接链接）',
    'Title' => '标题',
    '<strong>Custom</strong> Pages' => '<strong>自定义</strong> 页面',
    'Back to overview' => '返回概览',
    'Overview' => '概览',
    'Pages' => '页面',
    'Snippets' => '片段',
    'Templates' => '模版',
    'Please choose one of the following content types. The content type defines how your content is embeded to your site.' => '请选择以下内容类型的一个。内容类型定义了您的内容如何嵌入到您的网站上。',
    'Add' => '增加',
    'Iframe' => 'Iframe框架',
    'Template' => '模版',
    'Html' => 'Html网页',
    'Allows you to add content in MarkDown syntax.' => '允许你用Markdown语法添加内容。',
    'Adds plain HTML content to your site.' => '为你的网站添加HTML页面。',
    'Templates allow you to define combinable page fragments with inline edit functionality.' => '模板允许你使用内联编辑功能定义组合页面片段。',
    'Will embed the the result of a given url as an iframe element.' => '将一个给定的URL的页面内容嵌入到iframe元素。',
    'Will redirect requests to a given (relative or absolute) url.' => '将重定向到一个给定的（相对或绝对的）网址。',
    'Dashboard' => '控制面板',
    'Directory' => '目录',
    'Saved' => '已保存',
    'This container does not allow any further items!' => '此容器不允许任何进一步的项目！',
    'This action requires an ownerContentId or ownerContent instance!' => '此操作需要一个 ownerContentId 或者 ownerContent 的实例！',
    'This action requires an templateId or template instance!' => '此操作需要一个 templateId 的实例！',
    'General' => '常规',
    'Source' => '源',
    'Save' => '保存',
    'Create new {type}' => '创建新的 {type}',
    'Close' => '关闭',
    'Delete' => '删除',
    'Cancel' => '取消',
    'Layouts' => '布局',
    'Snipped-Layouts' => '片段布局',
    'Containers' => '容器',
    'Submit' => '提交',
    'An empty allowed template selection will allow all container templates for this container.' => '一个空的允许的模板选择将允许此容器的所有容器模板。',
    'Default Content' => '默认内容',
    'Content' => '内容',
    'Reset' => '重置',
    'Back' => '返回',
    '<strong>No file available.</strong>' => '<strong>没有可用文件。</strong>',
    'Upload' => '上传',
    '<strong>No image available.</strong>' => '<strong>没有可用图片。</strong>',
    'Edit On' => '打开编辑',
    'Edit Off' => '关闭编辑',
    'Edit Page' => '编辑页面',
    'Default' => '默认',
    'Empty' => '空的',
];
