<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'The element name must contain at least two characters without spaces or special signs except \'_\'' => '元素名称必须至少包含两个字符没有空格或特殊符号除了“_”',
    'Element name' => '元素名',
    'The given element name is already in use for this template.' => '给定的元素名称已在这个模板中使用。',
];
