<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Template not found!' => '没有找到模版！',
    '<strong>Add</strong> new {type} element' => '<strong>增加</strong> 新的 {type} 元素',
    '<strong>Edit</strong> element {name}' => '<strong>编辑</strong> 元素 {name}',
    'The template could not be deleted, please get sure that this template is not in use.' => '模版不能被删除，请确认该模版是不是在使用中。',
    '<strong>Edit</strong> default content of {templateName}' => '<strong>编辑</strong> {templateName} 的 默认内容',
    '<strong>Edit</strong> elements of {templateName}' => '<strong>编辑</strong> {templateName} 的元素',
];
