<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Edit template \'{templateName}\'' => '编辑 \'{templateName}\'',
    'Save' => '保存',
    'Edit All' => '编辑所有',
    'Add Element' => '增加元素',
    'You haven\'t saved your last changes yet. Do you want to leave without saving?' => '你还没有保存你的最后的变化。你想不保存就离开吗？',
    'Here you can edit the source of your template by defining the template layout and adding content elements. '
    . 'Each element can be assigned with a default content and additional definitions.' => '在这里，您可以通过定义模板布局和添加内容元素来编辑模板的源代码。每个元素都可以分配一个默认内容和附加定义。',
];