<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add a file icon before the title' => '',
    'Advanced' => '',
    'Alternate text' => '',
    'Close' => '',
    'Css Class' => '',
    'File' => '',
    'Html' => '',
    'Iframe' => '',
    'Item name' => '',
    'Save' => '',
    'Show additional file information (size)' => '',
    'Style' => '',
    'Upload image' => '',
    '<strong>Custom</strong> Pages' => '<strong>Eigene</strong> Seiten',
    '<strong>Edit</strong> snippet' => 'Schnipsel <strong>bearbeiten</strong>',
    'Add' => 'Hinzufügen',
    'Adds plain HTML content to your site.' => 'Reinen HTML Inhalt hinzufügen',
    'Allows to add pages (markdown, iframe or links) to the space navigation' => 'Ermöglicht das Anlegen eigener Seiten in der Navigation.',
    'Allows you to add content in MarkDown syntax.' => 'Ermöglicht es Ihnen Inhalt mit Markdown Syntax hinzuzufügen.',
    'An empty allowed template selection will allow all container templates for this container.' => 'Eine leere erlaubte Vorlagenauswahl wird allen Container Vorlagen hiermit zur Verfügung gestellt.',
    'Back' => 'Zurück',
    'Back to dashboard' => 'Zurück zum Dashboard',
    'Back to directory' => 'Zurück zum Verzeichnis',
    'Back to space' => 'Zurück zum Space',
    'Cancel' => 'Abbrechen',
    'Configuration' => 'Konfiguration',
    'Containers' => 'Container',
    'Content' => 'Inhalt',
    'Create new {type}' => '{type} erstellen',
    'Custom Pages' => 'Eigene Seiten',
    'Custom pages' => 'Eigene Seiten',
    'Dashboard' => 'Dashboard',
    'Default' => 'Standard',
    'Default Content' => 'Standard Inhalt',
    'Delete' => 'Löschen',
    'Directory' => 'Verzeichnis',
    'Edit' => 'Bearbeiten',
    'Edit Page' => 'Seite bearbeiten',
    'Empty' => 'Leer',
    'General' => 'Allgemein',
    'HTML' => 'HTML',
    'IFrame' => 'iFrame',
    'Layouts' => 'Vorlagen',
    'Link' => 'Link',
    'MarkDown' => 'MarkDown',
    'Navigation' => 'Navigation',
    'Off' => 'Aus',
    'On' => 'An',
    'Overview' => 'Übersicht',
    'Pages' => 'Seiten',
    'Please choose one of the following content types. The content type defines how your content is embeded to your site.' => 'Bitte wählen Sie einen der folgenden Inhaltstypen. Der Inhalttype bestimmt wie der Inhalt in Ihre Seite eingebunden wird.',
    'Reset' => 'Zurücksetzen',
    'Saved' => 'Gespeichert',
    'Snipped-Layouts' => 'Schnipsel Vorlagen',
    'Snippets' => 'Schnipsel',
    'Sort Order' => 'Sortierung',
    'Source' => 'Sourcecode',
    'Submit' => 'Senden',
    'Template' => 'Vorlage',
    'Templates' => 'Vorlagen',
    'Templates allow you to define combinable page fragments with inline edit functionality.' => 'Vorlagen erlauben es Ihnen kombinierbare Seiten Elemente mit bearbeitbarer inline Funktionalität zu definieren',
    'This action requires an ownerContentId or ownerContent instance!' => 'Diese Aktion benötigt eine ownerContentID oder eine ownerContent Instanz',
    'This action requires an templateId or template instance!' => 'Diese Aktion benötigt eine Vorlagen ID oder eine Vorlagen Instanz',
    'This container does not allow any further items!' => 'Dieser Container enthält keine weiteren Elemente',
    'Title' => 'Titel',
    'Top Navigation' => 'Obere Navigation',
    'Type' => 'Typ',
    'User Account Menu (Settings)' => 'Benutzermenü Einstellungen',
    'Will embed the the result of a given url as an iframe element.' => 'Wird den Inhalt einer URL als iFrame Element einbinden.',
    'Will redirect requests to a given (relative or absolute) url.' => 'Leitet Anfragen zu einer absoluten oder relativen URL weiter',
    'Without adding to navigation (Direct link)' => 'Ohne Berücksichtigung in der Navigation (Direkter Link)',
];
