<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Custom</strong> Pages' => '',
    '<strong>Edit</strong> snippet' => '',
    'Add' => '',
    'Add a file icon before the title' => '',
    'Adds plain HTML content to your site.' => '',
    'Advanced' => '',
    'Allows to add pages (markdown, iframe or links) to the space navigation' => '',
    'Allows you to add content in MarkDown syntax.' => '',
    'Alternate text' => '',
    'An empty allowed template selection will allow all container templates for this container.' => '',
    'Back' => '',
    'Back to dashboard' => '',
    'Back to directory' => '',
    'Back to space' => '',
    'Cancel' => '',
    'Close' => '',
    'Configuration' => '',
    'Containers' => '',
    'Content' => '',
    'Create new {type}' => '',
    'Css Class' => '',
    'Custom Pages' => '',
    'Custom pages' => '',
    'Dashboard' => '',
    'Default' => '',
    'Default Content' => '',
    'Delete' => '',
    'Directory' => '',
    'Edit' => '',
    'Edit Page' => '',
    'Empty' => '',
    'File' => '',
    'General' => '',
    'Html' => '',
    'IFrame' => '',
    'Iframe' => '',
    'Item name' => '',
    'Layouts' => '',
    'MarkDown' => '',
    'Off' => '',
    'On' => '',
    'Overview' => '',
    'Pages' => '',
    'Please choose one of the following content types. The content type defines how your content is embeded to your site.' => '',
    'Reset' => '',
    'Save' => '',
    'Saved' => '',
    'Show additional file information (size)' => '',
    'Snipped-Layouts' => '',
    'Snippets' => '',
    'Source' => '',
    'Style' => '',
    'Submit' => '',
    'Template' => '',
    'Templates' => '',
    'Templates allow you to define combinable page fragments with inline edit functionality.' => '',
    'This action requires an ownerContentId or ownerContent instance!' => '',
    'This action requires an templateId or template instance!' => '',
    'This container does not allow any further items!' => '',
    'Upload image' => '',
    'Will embed the the result of a given url as an iframe element.' => '',
    'Will redirect requests to a given (relative or absolute) url.' => '',
    'Without adding to navigation (Direct link)' => '',
    'HTML' => 'HTML',
    'Link' => 'Link',
    'Navigation' => 'Navigasjon',
    'Sort Order' => 'Sorterings Rekkefølge',
    'Title' => 'Tittel',
    'Top Navigation' => 'Top Navigering',
    'Type' => 'Type',
    'User Account Menu (Settings)' => 'Bruker konto meny (Innstillinger)',
];
