<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Allows to add pages (markdown, iframe or links) to the space navigation' => '',
    'Custom pages' => '',
    'Create new Page' => 'Створити нову сторінку',
    'Custom Pages' => 'Персональні сторінки',
    'HTML' => 'HTML',
    'IFrame' => 'IFrame',
    'Link' => 'Лінк',
    'MarkDown' => 'MarkDown',
    'Navigation' => 'Навігація',
    'No custom pages created yet!' => 'Персональні сторінки поки що відсутні!',
    'Sort Order' => 'Сортувати за номером',
    'Title' => 'Заголовок',
    'Top Navigation' => 'Верхня навігація',
    'Type' => 'Тип',
    'User Account Menu (Settings)' => 'Меню акаунта користувача (Налаштування)',
    'Without adding to navigation (Direct link)' => 'Без додавання в навігацію (Прямий лінк)',
];
