<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'More infos about the twig syntax is available <strong><a href="{twig_tmpl_url}">here</a></strong>' => '',
    'This template systems uses {twigLink} as template engine.<br /><br /> '
    . 'You can add elements as Richtexts or Images into your template by using the \'Add Element\' dropdown menu.<br />'
    . 'After adding an element, the elements placeholder is automatically inserted to your template.<br />'
    . 'You can change the position of your elements anytime. The element for an block with the name \'content\' '
    . 'will be represented as \'{{ content }}\' within your template.<br /><br /> The name of your block hast to start with an '
    . 'alphanumeric letter and cannot contain any special signs except an \'_\'. '
    . 'Each element provides additional placeholder for rendering the default content or edit links. '
    . 'These additions can be inserted adding for example {{ content.default }} to your template.' => '',
];