<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Allows to add pages (markdown, iframe or links) to the space navigation' => '',
    'Custom pages' => '',
    'Create new Page' => 'Dodaj stronę',
    'Custom Pages' => 'Własne strony',
    'HTML' => 'HTML',
    'IFrame' => 'IFrame',
    'Link' => 'Odnośnik',
    'MarkDown' => 'Znaczniki MarkDown',
    'Navigation' => 'Nawigacja',
    'No custom pages created yet!' => 'Nie stworzono jeszcze własnych stron!',
    'Sort Order' => 'Sortuj',
    'Title' => 'Tytuł',
    'Top Navigation' => 'Górna nawigacja',
    'Type' => 'Rodzaj',
    'User Account Menu (Settings)' => 'Konto użytkownika (Ustawienia)',
    'Without adding to navigation (Direct link)' => 'Bez dodawania do nawigacji (odnośnik bezpośredni)',
];
