<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Activate PHP based Pages and Snippets' => '',
    'If disabled, existing php pages will still be online, but can\'t be created.' => '',
    'PHP view path for custom space pages' => '',
    'PHP view path for custom space snippets' => '',
    'PHP view path for global custom pages' => '',
    'PHP view path for global custom snippets' => '',
    'The given view file path does not exist.' => '',
];
