<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Next' => '',
    '<strong>Create</strong> page' => '<strong>Opret</strong> side',
    '<strong>Edit</strong> page' => '<strong>Rediger</strong> side',
    'Content' => 'Indhold',
    'Default sort orders scheme: 100, 200, 300, ...' => 'Standard sorteringsrækkefølge: 100, 200, 300, ...',
    'Delete' => 'Slet',
    'Page title' => 'Side titel',
    'Save' => 'Gem',
    'Sort Order' => 'Sorteringsrækkefølge',
    'URL' => 'URL',
];
