name: Codeception Tests - master

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * 1"

jobs:
  tests:
    uses: humhub/module-coding-standards/.github/workflows/codeception-master.yml@main
    with:
      module-id: custom_pages
      install-composer: true
